---
apiVersion: v1
kind: Service
metadata:
  name: sammy-app
  labels:
    app: sammy-app
spec:
  type: ClusterIP
  ports:
    - name: sammy-app-http
      port: 80
      protocol: TCP
  selector:
    app: sammy-app
